# Generated by Django 5.0.2 on 2024-04-05 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=10000)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('treino', 'Aquecimento'), ('acrobacias', 'Acrobacia'), ('giro', 'Giro'), ('outro', 'Outro Tipo')], max_length=10)),
                ('dificuldade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('realizados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=2000)),
                ('nomeConta', models.CharField(max_length=100)),
                ('tempo', models.IntegerField()),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.movimento')),
            ],
        ),
    ]
